"""Export tiny FFN wake word models as C header files for ESP32 / ESP-IDF.

Generates a self-contained ``.h`` file with int8-quantized weights as C arrays
and a minimal inference function (two matmuls + ReLU + sigmoid). The generated
code has no runtime dependencies beyond standard C.

Only supports the ``FfnClassifierHead`` architecture (two linear layers).
"""
from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import torch

logger = logging.getLogger(__name__)


def export_to_c_header(
    model: torch.nn.Module,
    out_path: str,
    model_name: str = "ww_model",
    wake_word: str = "wake_word",
) -> None:
    """Export an FFN classifier head as a C header with int8 weights.

    The generated header contains:
    - Quantized int8 weight arrays and bias arrays
    - Scale factors for dequantization
    - A ``ww_model_infer(const float *input)`` function

    Args:
        model: A ``FfnClassifierHead`` or ``BaseWakeModel`` (the FFN head is extracted).
        out_path: Output ``.h`` file path.
        model_name: C identifier prefix for all generated symbols.
        wake_word: Wake word name (embedded as a comment).

    Raises:
        TypeError: If the model is not an FFN architecture.
    """
    from ww_trainer.model import FfnClassifierHead, BaseWakeModel

    # Extract the FFN head
    if isinstance(model, BaseWakeModel):
        head = model.classifier
    else:
        head = model

    if not isinstance(head, FfnClassifierHead):
        raise TypeError(
            f"export_to_c_header only supports FfnClassifierHead, got {type(head).__name__}"
        )

    # Extract weights
    state = head.state_dict()
    layers = []
    for i, key_prefix in enumerate(["sequential.0", "sequential.3"]):
        w = state[f"{key_prefix}.weight"].detach().cpu().numpy()
        b = state[f"{key_prefix}.bias"].detach().cpu().numpy()
        layers.append((w, b))

    # Quantize to int8
    quant_layers = []
    for w, b in layers:
        w_max = np.abs(w).max()
        w_scale = w_max / 127.0 if w_max > 0 else 1.0
        w_q = np.clip(np.round(w / w_scale), -128, 127).astype(np.int8)
        quant_layers.append((w_q, b.astype(np.float32), np.float32(w_scale)))

    input_dim = layers[0][0].shape[1]
    hidden_dim = layers[0][0].shape[0]

    # Generate C header
    lines = [
        f"/* Auto-generated by ww-trainer export_c.py */",
        f"/* Wake word: {wake_word} */",
        f"/* Architecture: FFN({input_dim}, {hidden_dim}, 1) */",
        f"/* Total params: {sum(w.size + b.size for w, b, _ in quant_layers)} */",
        f"#ifndef {model_name.upper()}_H",
        f"#define {model_name.upper()}_H",
        f"",
        f"#include <stdint.h>",
        f"#include <math.h>",
        f"",
        f"#define {model_name.upper()}_INPUT_DIM {input_dim}",
        f"#define {model_name.upper()}_HIDDEN_DIM {hidden_dim}",
        f"",
    ]

    # Emit weight arrays
    for i, (w_q, b, scale) in enumerate(quant_layers):
        rows, cols = w_q.shape
        lines.append(f"/* Layer {i}: [{rows}x{cols}], scale={scale:.8f} */")
        lines.append(f"static const float {model_name}_scale_{i} = {scale:.8f}f;")

        # Weight matrix
        lines.append(f"static const int8_t {model_name}_w{i}[{rows}][{cols}] = {{")
        for r in range(rows):
            vals = ", ".join(str(int(v)) for v in w_q[r])
            lines.append(f"  {{{vals}}},")
        lines.append("};")

        # Bias
        vals = ", ".join(f"{v:.8f}f" for v in b)
        lines.append(f"static const float {model_name}_b{i}[{rows}] = {{{vals}}};")
        lines.append("")

    # Emit inference function
    lines.extend([
        f"/* ReLU activation */",
        f"static inline float {model_name}_relu(float x) {{ return x > 0.0f ? x : 0.0f; }}",
        f"",
        f"/* Sigmoid activation */",
        f"static inline float {model_name}_sigmoid(float x) {{ return 1.0f / (1.0f + expf(-x)); }}",
        f"",
        f"/**",
        f" * Run wake word inference on pooled MFCC features.",
        f" * @param input Array of {input_dim} floats (mean-pooled MFCC frames).",
        f" * @return Wake word probability in [0, 1].",
        f" */",
        f"static float {model_name}_infer(const float input[{input_dim}]) {{",
        f"  float hidden[{hidden_dim}];",
        f"  /* Layer 0: Linear({input_dim}, {hidden_dim}) + ReLU */",
        f"  for (int i = 0; i < {hidden_dim}; i++) {{",
        f"    float sum = {model_name}_b0[i];",
        f"    for (int j = 0; j < {input_dim}; j++) {{",
        f"      sum += (float){model_name}_w0[i][j] * {model_name}_scale_0 * input[j];",
        f"    }}",
        f"    hidden[i] = {model_name}_relu(sum);",
        f"  }}",
        f"  /* Layer 1: Linear({hidden_dim}, 1) + Sigmoid */",
        f"  float logit = {model_name}_b1[0];",
        f"  for (int i = 0; i < {hidden_dim}; i++) {{",
        f"    logit += (float){model_name}_w1[i][0] * {model_name}_scale_1 * hidden[i];",
        f"  }}",
        f"  return {model_name}_sigmoid(logit);",
        f"}}",
        f"",
        f"#endif /* {model_name.upper()}_H */",
        f"",
    ])

    Path(out_path).write_text("\n".join(lines))
    total_bytes = sum(w.size for w, _, _ in quant_layers) + sum(b.size * 4 for _, b, _ in quant_layers)
    logger.info("Exported C header to %s (%d bytes int8 weights)", out_path, total_bytes)
